#!/usr/bin/env python
import rpa as r
import sys


class RFCSolver:
    URL = 'https://www.sat.gob.mx/tramites/operacion/28753/obten-tu-rfc-con-la-clave-unica-de-registro-de-poblacion-curp'
    URL_IFRAME = 'https://rfcampc.siat.sat.gob.mx/PTSC/IdcSiat/IDCPersonaFisicaCURP/TramiteInscripcionPersonaFisicaCURP.jsf'
    CURP_INPUT = '//*[@id="formContenido:curp"]'
    CAPTCHA_INPUT = '//*[@id="formContenido:captchaInput"]'
    LOGIN_BUTTON = '/html/body/div[3]/div/div/div/div[2]/form/div/div/div/div/div[3]/button[2]/span'
    CONTINUE_BUTTON = '//*[@id="formContenido:btnAceptarClic"]'
    POPUP = 'https://rfcampc.siat.sat.gob.mx/PTSC/IdcSiat/AcuseDomicilioContacto.jsf'

    def __init__(self, curp):
        self.curp = curp

    def solve(self):
        r.init(visual_automation=True)
        self.goto_page()
        self.login()
        self.fill()
        self.download()

    def goto_page(self):
        r.url(self.URL)
        r.wait(5)
        r.url(self.URL_IFRAME)
        r.wait(5)

    def login(self):
        r.type(self.CURP_INPUT, self.curp)
        captcha = r.ask()
        r.type(self.CAPTCHA_INPUT, captcha)
        r.click(self.LOGIN_BUTTON)
        r.mouse('down')
        r.click(self.CONTINUE_BUTTON)
        r.wait(5)

    def fill(self):
        r.type('//*[@id="formContenido:itCp"]', '22800')
        r.click('//*[@id="formContenido:somLocalidad_label"]')
        r.wait(1)
        r.click(
            '/html/body/div[3]/div/div/div/div[2]/form/div/div/div/div/div[1]/div[2]/table/tbody/tr/td[1]/table[1]/tbody/tr[4]/td[2]/div/div[3]')
        r.click('/html/body/div[32]/div[2]/ul/li[2]')
        r.click(
            '/html/body/div[3]/div/div/div/div[2]/form/div/div/div/div/div[1]/div[2]/table/tbody/tr/td[1]/table[1]/tbody/tr[4]/td[3]/div/div[3]/span')
        r.click('/html/body/div[33]/div[2]/ul/li[2]')
        r.type('//*[@id="formContenido:nombreCalle"]', 'B')
        r.type('//*[@id="formContenido:noExterior"]', '1')
        r.type('//*[@id="formContenido:entreCalle"]', '3')
        r.type('//*[@id="formContenido:yCalle"]', '1')
        r.mouse('down')
        r.type('//*[@id="formContenido:referencias"]', 'Cerca de tienda de autoservicio')
        r.click('//*[@id="formContenido:RegresarDetalle"]')
        r.wait(5)

    def download(self):
        r.popup(self.POPUP)
        r.wait(2)
        r.keyboard('[ctrl]p')
        r.keyboard('[enter]')


rfcSolver = RFCSolver(sys.argv[1])
rfcSolver.solve()
